# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

	#BOX
	config.vm.box = "puppetlabs/centos-7.0-64-puppet"

	#IP --> Para acceder por cable
	#config.vm.network "private_network", ip: "192.168.0.16"
	#config.vm.network "public_network", ip: "192.168.0.90"

	#IP --> Para acceder por wi-fi ??

	#IP --> Local
	config.vm.network :forwarded_port, guest: 80, host: 8000


	#carpetas compartidas
	config.vm.synced_folder "../shared/www", "/var/www/"

  #scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh"

	#Name
	config.vm.hostname = "Centos7-puppet4"

	#puppet 4.2.1
	config.vm.provision :puppet do |puppet|
    	puppet.environment_path = "environments"
    	puppet.environment = "development"
    	puppet.module_path = "modules"
	end

end
